application: jhtrnrdotcom
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /static
  static_dir: static

- url: /content
  static_dir: content

- url: /(.*)
  static_files: index.html
  upload: index.html

